name: vanboy
favicon: null
layout_spectrum: 0.87496
typography_spectrum: 0.28087
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0674352366477251
  lightness: 0.8741393538657576
  saturation: 0.75
  rhythmicContrast: 0.5761482692323625
purpose: []
